# Generated by Django 5.2 on 2025-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('drop', 'Drop'), ('inhaler', 'Inhaler')], max_length=50)),
                ('price_single', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_strip', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_pack', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_box', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
